#!/usr/bin/env python3
"""Assemble CHANGELOG.md's ``[Unreleased]`` section from per-card fragments.

WHY THIS EXISTS
---------------
CHANGELOG.md's ``[Unreleased]`` block used to be edited directly by every
worker. Because every card prepends into the *same* ``### Fixed`` / ``###
Verified`` hunk, two cards landing in the same window always conflicted
(confirmed on t_163fa09f @ ``7864796`` and t_9462260b @ merge ``29d5e97``,
landed @ ``f7f15d3`` — both collided in the same Unreleased/Fixed hunk, and
each collision cost a manual keep-both merge commit on the landing branch).

Now a card never edits ``CHANGELOG.md``. It adds one file, named after its own
kanban task id, under ``changelog.d/``:

    changelog.d/t_95f1d6e1.md

Two cards can never touch the same path, so concurrent diffs merge cleanly.
``[Unreleased]`` is a *generated view* of those fragments; the landing step
runs ``sync`` on the merge result, so the published CHANGELOG.md stays current.

FRAGMENT FORMAT (stdlib parser, no pip deps)
--------------------------------------------
One file per card. The file holds one or more entries; entries are separated by
a line containing exactly ``---``. Each entry is a ``kind:`` header line
followed by the entry body **verbatim** — write the body exactly as it should
appear under the ``### <Kind>`` heading (i.e. keep the leading ``- ``).

    kind: Fixed
    - **`doctor` false-failed on every dispatched worker.** …prose…
    ---
    kind: Verified
    - Full suite `scripts/run_tests.sh` **ALL GREEN** (9/9 packages).

Optional headers before the body: ``task: t_<id>`` (defaults to the file stem)
and ``order: <int>`` (defaults 0; breaks ties inside one file). Blank ``kind``
values, unknown header names and empty bodies are errors — a malformed
fragment must fail loudly in ``check`` rather than silently vanish at release.

ORDERING (deterministic, so re-running `sync` is a no-op)
--------------------------------------------------------
Kinds in Keep a Changelog order with HSCC's ``Verified`` last; unknown kinds
alphabetically after that. Within a kind: ``(task id, order, index-in-file)``.

COMMANDS
--------
    render              print the assembled [Unreleased] block
    sync                rewrite the [Unreleased] block in CHANGELOG.md
    check               exit 1 if CHANGELOG.md's block != assembled block
    add --task t_<id> --kind Fixed  append an entry to that card's fragment
                                    (reads the body from --body or stdin)

Exit codes: 0 ok, 1 drift/failed check, 2 usage or malformed fragment.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FRAGMENTS_DIR = REPO_ROOT / "changelog.d"
CHANGELOG = REPO_ROOT / "CHANGELOG.md"

UNRELEASED_HEADING = "## [Unreleased]"
# Anchor that marks the generated block as machine-managed. Humans should edit
# the fragment, not the block.
GENERATED_MARKER = (
    "<!-- GENERATED by scripts/changelog_fragments.py sync from changelog.d/*.md"
    " — do not edit here: add/edit a fragment file instead. -->"
)

# Keep a Changelog order; `Verified` is HSCC-specific and goes last.
KIND_ORDER = [
    "Added",
    "Changed",
    "Deprecated",
    "Removed",
    "Fixed",
    "Security",
    "Verified",
]

_HEADER_RE = re.compile(r"^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$")
_SEPARATOR = "---"
_ALLOWED_HEADERS = {"kind", "task", "order"}
TASK_ID_RE = re.compile(r"^t_[0-9a-f]{6,}$")


class FragmentError(Exception):
    """A fragment file cannot be parsed."""


class Entry:
    __slots__ = ("kind", "task", "order", "index", "body", "source")

    def __init__(self, kind, task, order, index, body, source):
        self.kind = kind
        self.task = task
        self.order = order
        self.index = index
        self.body = body  # verbatim lines, no trailing newlines
        self.source = source

    def sort_key(self):
        return (self.task, self.order, self.index)

    def __repr__(self):  # pragma: no cover - debug aid
        return f"Entry({self.kind}, {self.task}, {self.source})"


def parse_fragment(path: Path):
    """Parse one fragment file into a list of Entry."""
    text = path.read_text(encoding="utf-8")
    entries = []
    default_task = path.stem
    blocks = text.split("\n")
    # split on standalone separator lines
    chunks, cur = [], []
    for line in blocks:
        if line.strip() == _SEPARATOR:
            chunks.append(cur)
            cur = []
        else:
            cur.append(line)
    chunks.append(cur)

    for chunk in chunks:
        # drop leading/trailing blank lines only
        while chunk and not chunk[0].strip():
            chunk.pop(0)
        while chunk and not chunk[-1].strip():
            chunk.pop()
        if not chunk:
            continue
        if all(l.lstrip().startswith("#") for l in chunk):
            continue  # comment-only chunk

        headers = {}
        body_start = 0
        for i, line in enumerate(chunk):
            m = _HEADER_RE.match(line)
            if not m:
                if i == 0:
                    raise FragmentError(
                        f"{path.name}: first line must be a 'kind:' header, got "
                        f"{line!r}"
                    )
                body_start = i
                break
            key, val = m.group(1).lower(), m.group(2).strip()
            if key not in _ALLOWED_HEADERS:
                # Not a known header: treat as body start (prose may contain
                # "Note: ..." lines), unless it is the first line.
                body_start = i
                break
            headers[key] = val
        else:
            raise FragmentError(f"{path.name}: entry has headers but no body")

        kind = headers.get("kind", "").strip()
        if not kind:
            raise FragmentError(f"{path.name}: entry is missing a 'kind:' value")
        task = (headers.get("task") or "").strip() or default_task
        order_raw = (headers.get("order") or "0").strip()
        try:
            order = int(order_raw)
        except ValueError:
            raise FragmentError(
                f"{path.name}: 'order' must be an integer, got {order_raw!r}"
            )

        body = chunk[body_start:]
        # trailing blanks inside the body are noise
        while body and not body[-1].strip():
            body.pop()
        if not body:
            raise FragmentError(f"{path.name}: kind '{kind}' has an empty body")
        if not any(l.strip() for l in body if not l.lstrip().startswith("#")):
            raise FragmentError(f"{path.name}: kind '{kind}' has only comments")

        entries.append(
            Entry(kind=kind, task=task, order=order, index=len(entries),
                  body=body, source=path.name)
        )
    return entries


def load_entries(fragments_dir: Path = FRAGMENTS_DIR):
    entries = []
    if not fragments_dir.is_dir():
        return entries
    for path in sorted(fragments_dir.glob("*.md")):
        if path.name.lower().startswith("readme"):
            continue
        entries.extend(parse_fragment(path))
    return entries


def kind_sort_key(kind: str):
    try:
        return (0, KIND_ORDER.index(kind), "")
    except ValueError:
        return (1, 0, kind.lower())


def render_block(entries=None, fragments_dir: Path = FRAGMENTS_DIR,
                 marker: str = GENERATED_MARKER):
    """Return the full ``## [Unreleased]`` block text (no trailing newline)."""
    if entries is None:
        entries = load_entries(fragments_dir)
    by_kind = {}
    for e in entries:
        by_kind.setdefault(e.kind, []).append(e)

    out = [UNRELEASED_HEADING, ""]
    out.append(marker)
    out.append("")
    if not by_kind:
        out.append("_No unreleased fragments. Add `changelog.d/<task-id>.md`._")
        return "\n".join(out).rstrip("\n")

    for kind in sorted(by_kind, key=kind_sort_key):
        out.append(f"### {kind}")
        for e in sorted(by_kind[kind], key=Entry.sort_key):
            out.extend(e.body)
        out.append("")
    return "\n".join(out).rstrip("\n")


def split_changelog(text: str):
    """Return (preamble, block_or_None, postamble) around [Unreleased]."""
    lines = text.split("\n")
    try:
        start = next(i for i, l in enumerate(lines) if l.strip() == UNRELEASED_HEADING)
    except StopIteration:
        return text, None, ""
    end = len(lines)
    for i in range(start + 1, len(lines)):
        if re.match(r"^## \[", lines[i]):
            end = i
            break
    return "\n".join(lines[:start]), "\n".join(lines[start:end]), "\n".join(lines[end:])


def current_block(text: str):
    _, block, _ = split_changelog(text)
    if block is None:
        return None
    return block.rstrip("\n")


def normalize(block: str):
    """Compare-friendly form: drop the generated marker and blank noise."""
    lines = [l.rstrip() for l in (block or "").split("\n")]
    lines = [l for l in lines if l.strip() and l.strip() != GENERATED_MARKER]
    return "\n".join(lines)


def assemble(preamble: str, block: str, postamble: str) -> str:
    """Rebuild CHANGELOG.md text with `block` replacing [Unreleased]."""
    pre = preamble.rstrip("\n")
    parts = []
    if pre:
        parts.append(pre)
        parts.append("")
    parts.append(block.rstrip("\n"))
    post = postamble.strip("\n")
    if post:
        parts.append("")
        parts.append(post)
    return "\n".join(parts) + "\n"


def add_entry(task: str, kind: str, body: str, fragments_dir: Path = FRAGMENTS_DIR):
    """Append one entry to the card's fragment file, creating it if needed."""
    if not TASK_ID_RE.match(task):
        raise FragmentError(
            f"task id {task!r} must look like t_<8 hex> (the kanban task id)"
        )
    path = fragments_dir / f"{task}.md"
    body_lines = [l.rstrip() for l in body.replace("\r\n", "\n").split("\n")]
    while body_lines and not body_lines[-1].strip():
        body_lines.pop()
    while body_lines and not body_lines[0].strip():
        body_lines.pop(0)
    if not body_lines:
        raise FragmentError("empty body")
    if not body_lines[0].lstrip().startswith(("-", "*", "1.", "1)", "1]")):
        body_lines[0] = "- " + body_lines[0]

    fragments_dir.mkdir(parents=True, exist_ok=True)
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    chunk = [f"kind: {kind}", f"task: {task}", ""] + body_lines
    if text.strip():
        if not text.endswith("\n"):
            text += "\n"
        text += _SEPARATOR + "\n" + "\n".join(chunk) + "\n"
    else:
        text = "\n".join(chunk) + "\n"
    path.write_text(text, encoding="utf-8")
    return path


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        prog="changelog_fragments.py",
        description="Assemble CHANGELOG.md [Unreleased] from changelog.d/ fragments.",
    )
    ap.add_argument(
        "command",
        nargs="?",
        default="check",
        choices=["check", "sync", "render", "add", "list"],
        help="check (default) / sync / render / add / list",
    )
    ap.add_argument("--task", help="task id for `add` (e.g. t_95f1d6e1)")
    ap.add_argument("--kind", help="section for `add` (Fixed, Verified, …)")
    ap.add_argument("--body", help="entry body for `add` (else read stdin)")
    ap.add_argument("--changelog", default=str(CHANGELOG))
    ap.add_argument("--fragments-dir", default=str(FRAGMENTS_DIR))
    ap.add_argument("--no-marker", action="store_true",
                    help="render without the GENERATED marker (tests)")
    ns = ap.parse_args(argv)

    changelog = Path(ns.changelog)
    frag_dir = Path(ns.fragments_dir)
    marker = "" if ns.no_marker else GENERATED_MARKER

    try:
        entries = load_entries(frag_dir)
    except FragmentError as exc:
        print(f"malformed fragment: {exc}", file=sys.stderr)
        return 2

    if ns.command == "list":
        for e in sorted(entries, key=lambda e: (e.kind, e.sort_key())):
            print(f"{e.kind:<10} {e.task:<14} {e.source:<24} "
                  f"{(e.body[0][:60] if e.body else '')}")
        print(f"{len(entries)} entries from {frag_dir}")
        return 0

    if ns.command == "add":
        if not ns.task or not ns.kind:
            print("add requires --task and --kind", file=sys.stderr)
            return 2
        body = ns.body
        if body is None:
            if sys.stdin.isatty():
                print("no --body; type the entry then Ctrl-D", file=sys.stderr)
            body = sys.stdin.read()
        try:
            path = add_entry(ns.task, ns.kind, body, fragments_dir=frag_dir)
        except FragmentError as exc:
            print(f"cannot add entry: {exc}", file=sys.stderr)
            return 2
        print(f"wrote {path.relative_to(REPO_ROOT)}")
        return 0

    block = render_block(entries, fragments_dir=frag_dir, marker=marker)

    if ns.command == "render":
        sys.stdout.write(block + "\n")
        return 0

    if not changelog.exists():
        print(f"no changelog at {changelog}", file=sys.stderr)
        return 2
    text = changelog.read_text(encoding="utf-8")
    preamble, current, postamble = split_changelog(text)

    if ns.command == "sync":
        if normalize(current or "") == normalize(block):
            print(f"already in sync ({len(entries)} entries) — nothing to write")
            return 0
        new_text = assemble(preamble, block, postamble)
        tmp = changelog.with_name(changelog.name + ".tmp-frag")
        tmp.write_text(new_text, encoding="utf-8")
        os.replace(tmp, changelog)  # never leave a half-written changelog
        print(f"synced [Unreleased] from {len(entries)} fragment entries")
        return 0

    # check
    if normalize(current or "") == normalize(block):
        print(f"OK — [Unreleased] matches {len(entries)} fragment entries")
        return 0
    print(
        "DRIFT: CHANGELOG.md [Unreleased] does not match changelog.d/ fragments.\n"
        "If you added an entry, put it in changelog.d/<your-task-id>.md (not in\n"
        "CHANGELOG.md) and run: python3 scripts/changelog_fragments.py sync\n",
        file=sys.stderr,
    )
    import difflib

    for line in difflib.unified_diff(
        normalize(current or "").split("\n"), normalize(block).split("\n"),
        fromfile="CHANGELOG.md (as committed)", tofile="assembled from changelog.d/",
        lineterm="",
    ):
        print(line)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
