#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# hscc-daemon systemd --user Setup Helper (Linux)
#
# Installs, enables, and verifies the hscc-daemon systemd --user service.
# This is the Linux counterpart of launchd-setup.sh.
#
# Usage:
#   ./systemd-setup.sh          # Install, enable + start, verify (idempotent)
#   ./systemd-setup.sh force    # Re-install the unit, then restart
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DAEMON="${SCRIPT_DIR}/hscc.py"
UNIT_NAME="hscc-daemon.service"
UNIT_DIR="$HOME/.config/systemd/user"
UNIT_FILE="${UNIT_DIR}/${UNIT_NAME}"
LOG_FILE="$HOME/.hscc/daemon.log"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ── Pre-flight ──────────────────────────────────────────────────────────────
if ! command -v systemctl &>/dev/null; then
    error "systemctl not found — this script requires a systemd-based Linux"
    exit 1
fi

mkdir -p "${UNIT_DIR}" "$(dirname "${LOG_FILE}")"

# ── Install unit (generated by the daemon so paths resolve correctly) ────────
if [[ "${1:-}" == "force" ]] || [[ ! -f "${UNIT_FILE}" ]]; then
    python3 "${DAEMON}" plist > "${UNIT_FILE}"
    info "Installed unit to ${UNIT_FILE}"
else
    info "Unit already present at ${UNIT_FILE}"
fi

systemctl --user daemon-reload

# ── Enable + start ──────────────────────────────────────────────────────────
if [[ "${1:-}" == "force" ]]; then
    systemctl --user restart "${UNIT_NAME}" || true
fi
systemctl --user enable --now "${UNIT_NAME}"
info "Enabled + started ${UNIT_NAME}"

# Survive logout (no-op if already enabled or not permitted).
loginctl enable-linger "$USER" 2>/dev/null \
    && info "Lingering enabled — daemon survives logout" \
    || warn "Could not enable lingering (daemon stops on logout unless 'loginctl enable-linger $USER' is run as needed)"

# ── Status ──────────────────────────────────────────────────────────────────
echo ""
info "── hscc-daemon Service Status ────────────────────────────────────"
if systemctl --user is-active --quiet "${UNIT_NAME}"; then
    echo -e "  ${GREEN}●${NC} systemd:    active"
else
    echo -e "  ${RED}○${NC} systemd:    not active"
fi

if pgrep -f "hscc.py.*start-daemon" &>/dev/null; then
    PID=$(pgrep -f "hscc.py.*start-daemon" | head -1)
    echo -e "  ${GREEN}●${NC} Process:    running (PID ${PID})"
else
    echo -e "  ${RED}○${NC} Process:    not running (expected to be started by systemd)"
fi

if [[ -d "$HOME/.hscc/state" ]]; then
    COUNT=$(find "$HOME/.hscc/state" -name "*.json" 2>/dev/null | wc -l | tr -d ' ')
    echo -e "  ${GREEN}●${NC} State:      ${COUNT} JSON files in ~/.hscc/state/"
else
    echo -e "  ${RED}○${NC} State:      ~/.hscc/state/ not found"
fi

if [[ -f "${LOG_FILE}" ]]; then
    LINES=$(wc -l < "${LOG_FILE}" | tr -d ' ')
    echo -e "  ${GREEN}●${NC} Log:        ${LOG_FILE} (${LINES} lines)"
    echo ""
    echo -e "  ${YELLOW}── Tail last 10 log lines ────────────────────────────────────${NC}"
    tail -10 "${LOG_FILE}" | sed 's/^/    /'
else
    echo -e "  ${YELLOW}○${NC} Log:        ${LOG_FILE} (will be created on first run)"
fi

echo ""
info "── Management Commands ──────────────────────────────────────────"
echo "  Start:   systemctl --user start ${UNIT_NAME}"
echo "  Stop:    systemctl --user stop ${UNIT_NAME}"
echo "  Status:  systemctl --user status ${UNIT_NAME}"
echo "  Log:     tail -f ${LOG_FILE}"
echo "  Uninstall: ${DAEMON} uninstall"
echo ""
